# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build Docker
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    strategy:
      matrix:
        container:
          # End of standard support: April 2023 https://wiki.ubuntu.com/Releases
          - 'ubuntu:18.04'
#          # End of standard support: April 2025 https://wiki.ubuntu.com/Releases
#          - 'ubuntu:20.04'
#          # End of standard support: July 2022 https://wiki.ubuntu.com/Releases
#          - 'ubuntu:21.10'
#          # End of standard support: April 2027 https://wiki.ubuntu.com/Releases
#          - 'ubuntu:22.04'
#          # EOL ~August 2022 https://wiki.debian.org/DebianReleases
#          - 'debian:10-slim'
#          - 'debian:11-slim'
#          # EOL June 7 2022 https://endoflife.date/fedora
#          - 'fedora:34'
#          - 'fedora:35'
#          - 'fedora:36'
#          # EOL May 2024 https://www.centos.org/centos-stream/
#          - 'quay.io/centos/centos:stream8'
        cc: ['gcc']
        buildtype: ['debug', 'release']

    # use the oldest kernel supported by github's CI (make sure to update the
    # minimum supported kernel version in documentation when changing)
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        # Run on PR head instead of merge result. Running on the merge
        # result can give confusing results, and we require PR to be up to
        # date with target branch before merging, anyway.
        # See https://github.com/shadow/shadow/issues/2166
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        # Replace the single ':' with a '-'
        CONTAINER_FOR_TAG=${${{ matrix.container }}/:/-}
        # Replace all forward slashes with '-'
        CONTAINER_FOR_TAG="${CONTAINER_FOR_TAG//\//-}"
        # FIXME: use a shadow dockerhub account
        TAG="sporksmith/shadow-ci:$CONTAINER_FOR_TAG-$CC-$BUILDTYPE"

        docker build . -t "${TAG}"" --shm-size="1g"
        docker run --shm-size="1g" --privileged --rm --entrypoint /src/ci/container_scripts/test.sh --build-arg "CONTAINER=${{ matrix.container }},CC=${{ matrix.cc}},BUILDTYPE=${{ matrix.buildtype }}" "${TAG}"
        # FIXME
        docker login -u sporksmith --password "${{ secrets.DOCKERHUB_TOKEN }}"
        docker push "${TAG}""
